### ISSUE TITLE
Canvas - Length of task_output is too long

### ISSUE THREAD

**Issue by shaidar** [mitodl/edx-platform#188]
Certain large courses receive a response from Canvas larger than the field lengths set for task_output in instructor_task models, thus throwing an error. Specifically the `push_edx_grades_to_canvas_task` results in the below trace on certain courses:
```
CRITICAL 32039 [celery.worker.job] [user None] log.py:282 - Task lms.djangoapps.canvas_integration.tasks.push_edx_grades_to_canvas_task[09509efd-dca8-48b7-b444-156407ea510f] INTERNAL ERROR: ValueError('Length of task output is too long: {"duration_ms": 410120, "failed": 0, "action_name": "push_edx_grades_to_canvas", "succeeded": 0, "results": {"grades": {"Pre-Lecture 8": "updated", "Lecture 10": "updated", "Pre-lecture 5 clickers": "updated", "Pre-Lecture 4": "updated", "Lecture 11": "updated", "Pre-Lecture 9": "updated", "Pre-Lecture 13": "updated", "Lecture 4 clickers": "updated", "Pre-Lecture 10": "updated", "lecture 13 clicker questions": "updated", "Lecture 6 clickers": "updated", "Lecture 1 clickers": "updated", "Lecture 2 clickers": "updated", "Pre-Lecture 11 -MOT": "updated", "Lecture 7 clickers": "updated", "Online Problems 1": "updated", "pre-lecture 12: VB Pre-Lecture": "updated", "Lecture 3 clickers": "updated", "Pre-Lecture 3": "updated", "Online Problem Set 2": "updated", "Lecture 12 clicker questions": "updated", "Lecture 9": "updated", "Lecture 5 clickers": "updated", "Pre-Lecture 7 clickers": "updated", "Lecture 8": "updated", "Pre-lecture 6": "updated", "Pre-Lecture 2": "updated"}, "assignments": {"Pre-Lecture 14": "created", "Pre-Lecture 15": "created", "Pre-Lecture 16- intermolecular interactions": "created", "Lecture 16": "created", "Lecture 14 clickers": "created", "Lecture 15": "created", "On-line Problem Set 3": "created"}}, "step": "Done", "preassigned": 0, "skipped": 0, "attempted": 0, "total": 1}',)
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/celery/app/trace.py", line 289, in trace_task
    task_on_success(retval, uuid, args, kwargs)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/tasks_base.py", line 66, in on_success
    entry.task_output = InstructorTask.create_output_for_success(task_progress)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/models.py", line 151, in create_output_for_success
    raise ValueError(u"Length of task output is too long: {0}".format(json_output))
ValueError: Length of task output is too long: {"duration_ms": 410120, "failed": 0, "action_name": "push_edx_grades_to_canvas", "succeeded": 0, "results": {"grades": {"Pre-Lecture 8": "updated", "Lecture 10": "updated", "Pre-lecture 5 clickers": "updated", "Pre-Lecture 4": "updated", "Lecture 11": "updated", "Pre-Lecture 9": "updated", "Pre-Lecture 13": "updated", "Lecture 4 clickers": "updated", "Pre-Lecture 10": "updated", "lecture 13 clicker questions": "updated", "Lecture 6 clickers": "updated", "Lecture 1 clickers": "updated", "Lecture 2 clickers": "updated", "Pre-Lecture 11 -MOT": "updated", "Lecture 7 clickers": "updated", "Online Problems 1": "updated", "pre-lecture 12: VB Pre-Lecture": "updated", "Lecture 3 clickers": "updated", "Pre-Lecture 3": "updated", "Online Problem Set 2": "updated", "Lecture 12 clicker questions": "updated", "Lecture 9": "updated", "Lecture 5 clickers": "updated", "Pre-Lecture 7 clickers": "updated", "Lecture 8": "updated", "Pre-lecture 6": "updated", "Pre-Lecture 2": "updated"}, "assignments": {"Pre-Lecture 14": "created", "Pre-Lecture 15": "created", "Pre-Lecture 16- intermolecular interactions": "created", "Lecture 16": "created", "Lecture 14 clickers": "created", "Lecture 15": "created", "On-line Problem Set 3": "created"}}, "step": "Done", "preassigned": 0, "skipped": 0, "attempted": 0, "total": 1}
```

It appears that the max_length for the `task_output` field is set to `1024` and then there's a [check[(https://github.com/mitodl/edx-platform/blob/mitx/juniper-stable/lms/djangoapps/instructor_task/models.py#L150) for a hardcoded value of `1023`.
When the task raises the ValueError above, it doesn't make it to the instructor dashboard and so the task remains in pending tasks with an `incomplete` status

**Comment by pdpinch** [comment]
I believe this was fixed by #189
