### ISSUE TITLE
Ginkgo: ORA2 Editing Bug

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/edx-platform#57]
The issue described in https://github.mit.edu/mitx/Spring-2018/issues/28 is due to a bug in the Javascript which fails when trying to submit the page edit. The stack trace is:
```
Error: Mismatched anonymous define() module: function (c,d){return a.Backgrid=b(c,d)}
http://requirejs.org/docs/errors.html#mismatch
    at makeError (https://studio-mitx-qa-next.mitx.mit.edu/static/1a3fbc1/mitx-theme/js/cms-base-vendor.cc46c56551ca.js:16219:17)
    at intakeDefines (https://studio-mitx-qa-next.mitx.mit.edu/static/1a3fbc1/mitx-theme/js/cms-base-vendor.cc46c56551ca.js:17305:36)
    at Object.localRequire [as require] (https://studio-mitx-qa-next.mitx.mit.edu/static/1a3fbc1/mitx-theme/js/cms-base-vendor.cc46c56551ca.js:17497:21)
    at requirejs (https://studio-mitx-qa-next.mitx.mit.edu/static/1a3fbc1/mitx-theme/js/cms-base-vendor.cc46c56551ca.js:17848:24)
    at eval (eval at globalEval (https://studio-mitx-qa-next.mitx.mit.edu/static/1a3fbc1/mitx-theme/js/cms-base-vendor.cc46c56551ca.js:487:5), <anonymous>:1:1)
    at eval (<anonymous>)
    at Function.globalEval (https://studio-mitx-qa-next.mitx.mit.edu/static/1a3fbc1/mitx-theme/js/cms-base-vendor.cc46c56551ca.js:487:5)
    at domManip (https://studio-mitx-qa-next.mitx.mit.edu/static/1a3fbc1/mitx-theme/js/cms-base-vendor.cc46c56551ca.js:5435:15)
    at jQuery.fn.init.replaceWith (https://studio-mitx-qa-next.mitx.mit.edu/static/1a3fbc1/mitx-theme/js/cms-base-vendor.cc46c56551ca.js:5678:10)
    at jQuery.fn.init.jQuery.fn.(anonymous function) [as replaceAll] (https://studio-mitx-qa-next.mitx.mit.edu/static/1a3fbc1/mitx-theme/js/cms-base-vendor.cc46c56551ca.js:5709:37)
```

**Comment by pdpinch** [comment]
Does this happen in Ficus? On edx.org?

What version of ORA XBlock are we running right now?

**Comment by blarghmatey** [comment]
The ORA version that we are using is `ora2==1.4.6`

**Comment by pdpinch** [comment]
@NotoriousMKD has confirmed that this issue existed on edge.edx.org which means that it's most likely in master. We can close this after we confirm that edX has opened a ticket for it.

**Comment by pdpinch** [comment]
There's a JIRA ticket at edX for this, https://openedx.atlassian.net/browse/TNL-6916
