### ISSUE TITLE
Rescore if Improves, Rescore, and Override Score don't work for usernames with `@` in them

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#93]
Rescore if Improves, Rescore, and Override Score functions in the instructor dashboard (student admin) don't work for users with `@` in their username. 

from https://github.mit.edu/mitx/Summer-2018/issues/16

> The Rescore if Improves, Rescore, and Override Score functions don't work on touchstone user accounts via the Student Admin dashboard or the Staff Debug button at the problem. They don't work using the email address or the username associated with the learner. 
>
> The task status output shows this: 
![screenshot 2018-05-22 17 27 00](https://github.mit.edu/storage/user/9183/files/6339a428-5de5-11e8-82c9-263e3fa5a06a)
>
> You can test it with any of the first 5 problems on this [page](https://mitx-qa-next.mitx.mit.edu/courses/course-v1:MITx+mkd.0001+2018_Summer/courseware/ae9a2b2e5e1e41a5b6696ede0d7f60eb/5db32df5bb9b43f0ae9d3d873832f0a7/1?activate_block_id=block-v1%3AMITx%2Bmkd.0001%2B2018_Summer%2Btype%40vertical%2Bblock%40e04fff4c968347539321707399a986f6) using my touchstone user account username mkdaviesmit_1@touchstonenetwor or email mkdaviesmit@gmail.com
>
> The Reset Attempts to Zero and Delete Learner's State functions do work and all the functions work for non touchstone users.

**Comment by amir-qayyum-khan** [comment]
@pdpinch i dont see issue on `mitx/hawthorn` because `@` sign is already handle here

**Comment by amir-qayyum-khan** [comment]
Found this on running task

```  
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/tasks.py", line 94, in override_problem_score
    return run_main_task(entry_id, visit_fcn, action_name)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/tasks_helper/runner.py", line 113, in run_main_task
    task_progress = task_fcn(entry_id, course_id, task_input, action_name)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/tasks_helper/module_state.py", line 84, in perform_module_state_update
    course_id, usage_keys, student_identifier, filter_fcn, override_score_task
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/tasks_helper/module_state.py", line 423, in _get_modules_to_update
    student = get_student()
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/tasks_helper/module_state.py", line 417, in get_student
    return User.objects.get(**student_query_params)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: User matching query does not exist.
```

**Comment by pdpinch** [comment]
This was fixed upstream
